// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as State$Todo from "./state.bs.js";
import * as Template$Todo from "./template.bs.js";

Curry._2(window.addEventListener, "load", State$Todo.init);

Curry._2(window.addEventListener, "state-update", (function (x) {
        return Template$Todo.render(Template$Todo.template(x.detail), "app");
      }));

export {
  
}
/*  Not a pure module */
