// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function update(newState) {
  window.dispatchEvent(new CreateEvent("state-update", {
            detail: newState
          }));
  return newState;
}

function addTodo(state, todo) {
  var _todo_id = Uuid.v4();
  var _todo_title = todo.title;
  var _todo_description = todo.description;
  var _todo_createdAt = Date.now();
  var _todo = {
    id: _todo_id,
    title: _todo_title,
    description: _todo_description,
    createdAt: _todo_createdAt
  };
  return update({
              error: state.error,
              list: Belt_Array.concat(state.list, [_todo])
            });
}

function clearError(state) {
  return update({
              error: "",
              list: state.list
            });
}

function removeTodo(state, id) {
  var x = Belt_Array.keep(state.list, (function (x) {
          return x.id !== id;
        }));
  return update({
              error: state.error,
              list: x
            });
}

function setError(state, error) {
  return update({
              error: error,
              list: state.list
            });
}

export {
  addTodo ,
  clearError ,
  removeTodo ,
  setError ,
  
}
/* uuid Not a pure module */
