// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function addTodo(state, todo) {
  var newState = {
    list: Belt_Array.concat(state.list, [todo])
  };
  window.dispatchEvent(new CreateEvent("state-update", {
            detail: newState
          }));
  return newState;
}

export {
  addTodo ,
  
}
/* No side effect */
