// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as State$Todo from "./state.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function errorBubble(__x) {
  return Belt_Option.mapWithDefault(__x, "", (function (x) {
                return "<div class=\"error-msg\">" + x + "</div>";
              }));
}

function form(state) {
  return "\n	<form class=\"container form\">\n		" + errorBubble(state.error) + "\n		<label class=\"form__field\">\n			<span class=\"form__field--text\">Don't</span>\n			<input class=\"form__field--input\" id=\"text\" name=\"text\" type=\"text\" />\n		</label>\n		<button class=\"form__button\" id=\"add-todo\">Add Todon't</button>\n	</form>\n";
}

function makeTodo(todo) {
  return "\n	<article class=\"list__item\" id=\"" + todo.id + "\">" + todo.text + "</article>\n";
}

function todoList(list) {
  return "\n	<section class=\"container list\" id=\"todo-list\">\n		" + Belt_Array.joinWith(list, "\n", makeTodo) + "\n	</section>\n";
}

function events(state, id) {
  document.getElementById(id).addEventListener("click", (function (param) {
          param.preventDefault();
          var match = param.target.id;
          if (match === "add-todo") {
            return State$Todo.addTodo(state, {
                        text: document.getElementById("text").value
                      });
          } else {
            return state;
          }
        }));
  
}

function template(state) {
  return "\n	" + form(state) + "\n	" + todoList(state.list) + "\n";
}

function render(html, id) {
  var tmp = document.getElementById(id);
  tmp.innerHTML = html;
  var body = document.body;
  body.innerHTML = body.innerHTML;
  return id;
}

export {
  events ,
  render ,
  template ,
  
}
/* State-Todo Not a pure module */
